server:
  port: 8081
  servlet:
    context-path: /test
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_test?serverTimezone=UTC&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
  flyway:
    locations: classpath:/db/migration
    out-of-order: true
    enabled: true
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ty.springbootdemo.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
  level:
    root: info
  config: classpath:logback.xml
  file:
    path: ./logs
